#!/usr/bin/env bash
#
# LabRat - Shell Integration Management
# Handles PATH, tool initialization, and shell config backups
#

# shellcheck source=./common.sh
source "${LABRAT_LIB_DIR:-$(dirname "${BASH_SOURCE[0]}")}/common.sh"

# ============================================================================
# Shell Configuration Paths
# ============================================================================

LABRAT_SHELL_CONFIG_DIR="${LABRAT_CONFIG_DIR}/labrat"
LABRAT_SHELL_RC="${LABRAT_SHELL_CONFIG_DIR}/shellrc.sh"
LABRAT_SHELL_BACKUP_DIR="${LABRAT_DATA_DIR}/shell_backups"

# ============================================================================
# Backup Functions
# ============================================================================

# Backup original shell config files (one-time, before any modifications)
backup_original_shell_configs() {
    ensure_dir "$LABRAT_SHELL_BACKUP_DIR"
    
    local backed_up=0
    
    # Backup bashrc if exists and not already backed up
    if [[ -f "$HOME/.bashrc" ]] && [[ ! -f "${LABRAT_SHELL_BACKUP_DIR}/bashrc.original" ]]; then
        cp "$HOME/.bashrc" "${LABRAT_SHELL_BACKUP_DIR}/bashrc.original"
        log_info "Backed up original ~/.bashrc"
        ((backed_up++))
    fi
    
    # Backup zshrc if exists and not already backed up
    if [[ -f "$HOME/.zshrc" ]] && [[ ! -f "${LABRAT_SHELL_BACKUP_DIR}/zshrc.original" ]]; then
        cp "$HOME/.zshrc" "${LABRAT_SHELL_BACKUP_DIR}/zshrc.original"
        log_info "Backed up original ~/.zshrc"
        ((backed_up++))
    fi
    
    # Backup profile if exists and not already backed up
    if [[ -f "$HOME/.profile" ]] && [[ ! -f "${LABRAT_SHELL_BACKUP_DIR}/profile.original" ]]; then
        cp "$HOME/.profile" "${LABRAT_SHELL_BACKUP_DIR}/profile.original"
        log_info "Backed up original ~/.profile"
        ((backed_up++))
    fi
    
    if [[ $backed_up -gt 0 ]]; then
        log_success "Original shell configs backed up to: ${LABRAT_SHELL_BACKUP_DIR}/"
    fi
}

# Restore original shell configs (for uninstall)
restore_original_shell_configs() {
    local restored=0
    
    if [[ -f "${LABRAT_SHELL_BACKUP_DIR}/bashrc.original" ]]; then
        cp "${LABRAT_SHELL_BACKUP_DIR}/bashrc.original" "$HOME/.bashrc"
        log_success "Restored original ~/.bashrc"
        ((restored++))
    fi
    
    if [[ -f "${LABRAT_SHELL_BACKUP_DIR}/zshrc.original" ]]; then
        cp "${LABRAT_SHELL_BACKUP_DIR}/zshrc.original" "$HOME/.zshrc"
        log_success "Restored original ~/.zshrc"
        ((restored++))
    fi
    
    if [[ -f "${LABRAT_SHELL_BACKUP_DIR}/profile.original" ]]; then
        cp "${LABRAT_SHELL_BACKUP_DIR}/profile.original" "$HOME/.profile"
        log_success "Restored original ~/.profile"
        ((restored++))
    fi
    
    return $restored
}

# ============================================================================
# LabRat Shell Config Generation
# ============================================================================

# Initialize/update the LabRat shell config file
# This file is sourced early in bashrc/zshrc
init_labrat_shell_config() {
    ensure_dir "$LABRAT_SHELL_CONFIG_DIR"
    
    # Create/update the shell config file
    cat > "$LABRAT_SHELL_RC" << 'SHELL_CONFIG_HEADER'
#!/usr/bin/env bash
#
# LabRat Shell Configuration
# This file is auto-generated by LabRat installer
# Sourced early in your shell config for proper PATH and tool initialization
#
# To uninstall: labrat-uninstall or restore from ~/.local/share/labrat/shell_backups/
#

# ============================================================================
# PATH Configuration (must come first!)
# ============================================================================

# Add LabRat bin directory to PATH
if [ -d "$HOME/.local/bin" ] && [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

SHELL_CONFIG_HEADER
    
    chmod +x "$LABRAT_SHELL_RC"
    log_debug "Created LabRat shell config: $LABRAT_SHELL_RC"
}

# Add a tool's shell integration to the LabRat shell config
# Usage: add_shell_integration "tool_name" "eval_command" ["comment"]
add_shell_integration() {
    local tool_name="$1"
    local eval_cmd="$2"
    local comment="${3:-$tool_name initialization}"
    
    # Ensure shell config exists
    if [[ ! -f "$LABRAT_SHELL_RC" ]]; then
        init_labrat_shell_config
    fi
    
    # Check if already added
    if grep -qF "# $tool_name" "$LABRAT_SHELL_RC" 2>/dev/null; then
        log_debug "$tool_name integration already in shell config"
        return 0
    fi
    
    # Add the integration
    cat >> "$LABRAT_SHELL_RC" << EOF

# $tool_name - $comment
if command -v $tool_name &>/dev/null; then
    $eval_cmd
fi
EOF
    
    log_debug "Added $tool_name integration to shell config"
}

# Remove a tool's shell integration
remove_shell_integration() {
    local tool_name="$1"
    
    if [[ ! -f "$LABRAT_SHELL_RC" ]]; then
        return 0
    fi
    
    # Remove the section for this tool (from comment to next section or EOF)
    local temp_file=$(mktemp)
    awk -v tool="$tool_name" '
        /^# '"$tool_name"'/ { skip=1; next }
        /^# [a-zA-Z]/ { skip=0 }
        !skip { print }
    ' "$LABRAT_SHELL_RC" > "$temp_file"
    mv "$temp_file" "$LABRAT_SHELL_RC"
    
    log_debug "Removed $tool_name integration from shell config"
}

# ============================================================================
# Shell RC File Management
# ============================================================================

# Add LabRat source line to shell config (at the TOP, after interactive check)
install_shell_hook() {
    local shell_type="${1:-bash}"
    local shell_rc
    
    case "$shell_type" in
        bash) shell_rc="$HOME/.bashrc" ;;
        zsh)  shell_rc="$HOME/.zshrc" ;;
        *)    shell_rc="$HOME/.bashrc" ;;
    esac
    
    if [[ ! -f "$shell_rc" ]]; then
        log_warn "Shell config not found: $shell_rc"
        return 1
    fi
    
    local source_line="source \"$LABRAT_SHELL_RC\"  # LabRat shell integration"
    
    # Check if already hooked
    if grep -qF "LabRat shell integration" "$shell_rc" 2>/dev/null; then
        log_debug "LabRat hook already in $shell_rc"
        return 0
    fi
    
    # Backup original if first time
    backup_original_shell_configs
    
    # For bash, insert after the interactive check (after 'case $- in' block)
    # For zsh, insert near the top
    local temp_file=$(mktemp)
    
    if [[ "$shell_type" == "bash" ]]; then
        # Find line after "esac" (end of interactive check) and insert there
        awk -v line="$source_line" '
            /^esac$/ && !inserted {
                print
                print ""
                print "# LabRat: Load shell configuration early (PATH, tool inits)"
                print line
                print ""
                inserted=1
                next
            }
            { print }
        ' "$shell_rc" > "$temp_file"
        
        # If esac not found, prepend to file
        if ! grep -q "LabRat shell integration" "$temp_file"; then
            {
                echo "# LabRat: Load shell configuration early (PATH, tool inits)"
                echo "$source_line"
                echo ""
                cat "$shell_rc"
            } > "$temp_file"
        fi
    else
        # For zsh, just prepend
        {
            echo "# LabRat: Load shell configuration early (PATH, tool inits)"
            echo "$source_line"
            echo ""
            cat "$shell_rc"
        } > "$temp_file"
    fi
    
    mv "$temp_file" "$shell_rc"
    log_success "Installed LabRat hook in $shell_rc"
}

# Remove LabRat hook from shell config
remove_shell_hook() {
    local shell_type="${1:-bash}"
    local shell_rc
    
    case "$shell_type" in
        bash) shell_rc="$HOME/.bashrc" ;;
        zsh)  shell_rc="$HOME/.zshrc" ;;
        *)    shell_rc="$HOME/.bashrc" ;;
    esac
    
    if [[ ! -f "$shell_rc" ]]; then
        return 0
    fi
    
    local temp_file=$(mktemp)
    grep -v "LabRat shell integration\|LabRat: Load shell configuration" "$shell_rc" > "$temp_file"
    mv "$temp_file" "$shell_rc"
    
    log_info "Removed LabRat hook from $shell_rc"
}

# ============================================================================
# Full Setup
# ============================================================================

# Complete shell integration setup
setup_shell_integration() {
    log_step "Setting up shell integration..."
    
    # Backup original configs first
    backup_original_shell_configs
    
    # Create/update LabRat shell config
    init_labrat_shell_config
    
    # Install hooks in shell configs
    if [[ -f "$HOME/.bashrc" ]]; then
        install_shell_hook "bash"
    fi
    
    if [[ -f "$HOME/.zshrc" ]]; then
        install_shell_hook "zsh"
    fi
    
    log_success "Shell integration configured!"
    log_info "Shell config: $LABRAT_SHELL_RC"
    log_info "Backups: $LABRAT_SHELL_BACKUP_DIR/"
}

# Complete uninstall of shell integration
uninstall_shell_integration() {
    log_step "Removing shell integration..."
    
    # Remove hooks
    remove_shell_hook "bash"
    remove_shell_hook "zsh"
    
    # Remove LabRat shell config
    rm -f "$LABRAT_SHELL_RC"
    
    # Optionally restore originals
    if confirm "Restore original shell configs from backup?" "n"; then
        restore_original_shell_configs
    fi
    
    log_success "Shell integration removed"
}
